stages:
  - build
  #- test
  #- deploy

variables:
  AWS_PRIVATE_KEY: $AWS_PRIVATE_KEY  # Define your AWS private key variable here.

backend_build:
  stage: build
  image: maven:3.8.4-jdk-11  # Use a Maven image with Java 11.

  script:
    - mvn clean package

  artifacts:
    paths:
      - /builds/eduplanet2/education_planetcms/Edu_planet/ep_Backend_Project/ep_backend
      