image: abhishek/maven-abhishek-docker-agent:v1
variables:
  AWS_PRIVATE_KEY: $AWS_PRIVATE_KEY  # Define your AWS private key variable here.


stages:
  - build
  - test
  - deploy

variables:
  AWS_PRIVATE_KEY: $AWS_PRIVATE_KEY  # Define your AWS private key variable here.

backend_build:
  stage: build
  image: maven:3.8.4-jdk-11  # Use a Maven image with Java 11.

  script:
    - mvn clean package

  artifacts:
    paths:
      - /builds/eduplanet2/education_planetcms/Edu_planet/ep_Backend_Project/ep_backend
      
backend_test:
  stage: test
  image: maven:3.8.4-jdk-11  # Use the same Maven image for testing.

  script:
    - mvn test

backend_deploy:
  stage: deploy
  only:
    - master  # You might want to deploy only when changes are pushed to the master branch.
  
  script:
     #apt-get update && apt-get install -y openssh-client  # Install SSH client for scp and ssh commands.
    - scp -i $AWS_PRIVATE_KEY target/your-backend.jar ec2-user@3.108.21.241:/path/to/deployment/
    - ssh -i $AWS_PRIVATE_KEY ec2-user@3.108.21.241 "java -jar /path/to/deployment/your-backend.jar"
